// --- APP DATA & DICTIONARIES ---

const ROSTER_SECTIONS = [
  { heading: "h2", text: "1. The Confirmed Roster (117)", subsections: [
      { heading: "h3", text: "Kanto", lines: ["Bulbasaur / Ivysaur / Venusaur", "Charmander / Charmeleon / Charizard", "Squirtle / Wartortle / Blastoise", "Pichu / Pikachu / Raichu", "Gastly / Haunter / Gengar", "Kangaskhan", "Staryu / Starmie", "Pinsir", "Magikarp / Gyarados", "Dratini / Dragonair / Dragonite"] },
      { heading: "h3", text: "Johto", lines: ["Totodile / Croconaw / Feraligatr", "Scyther / Scizor", "Heracross", "Larvitar / Pupitar / Tyranitar"] },
      { heading: "h3", text: "Hoenn", lines: ["Ralts / Kirlia / Gardevoir|Gallade", "Feebas / Milotic", "Beldum / Metang / Metagross"] },
      { heading: "h3", text: "Sinnoh", lines: ["Piplup / Prinplup / Empoleon", "Gible / Gabite / Garchomp", "Riolu / Lucario"] },
      { heading: "h3", text: "Unova", lines: ["Snivy / Servine / Serperior", "Oshawott / Dewott / Samurott", "Cottonee / Whimsicott", "Emolga", "Deino / Zweilous / Hydreigon"] },
      { heading: "h3", text: "Kalos", lines: ["Chespin / Quilladin / Chesnaught", "Fennekin / Braixen / Delphox", "Froakie / Frogadier / Greninja", "Fletchling / Fletchinder / Talonflame", "Honedge / Doublade / Aegislash", "Hawlucha"] },
      { heading: "h3", text: "Alola", lines: ["Litten / Torracat / Incineroar", "Bounsweet / Steenee / Tsareena", "Oranguru", "Jangmo-o / Hakamo-o / Kommo-o"] },
      { heading: "h3", text: "Galar & Hisui", lines: ["Hatenna / Hattrem / Hatterene", "Dreepy / Drakloak / Dragapult", "Teddiursa / Ursaring / Ursaluna", "Basculin / Basculegion", "Hisuian Sneasel / Sneasler"] },
      { heading: "h3", text: "Paldea", lines: ["Tandemaus / Maushold", "Tinkatink / Tinkatuff / Tinkaton", "Finizen / Palafin", "Dondozo", "Tatsugiri", "Pawniard / Bisharp / Kingambit", "Poltchageist / Sinistcha", "Duraludon / Archaludon"] }
  ]},
  { heading: "h2", text: "2. Completing the Sets (28)", subsections: [
      { heading: null, text: null, lines: ["Eevee / Vaporeon|Jolteon|Flareon|Espeon|Umbreon|Leafeon|Glaceon|Sylveon", "Chikorita / Bayleef / Meganium", "Cyndaquil / Quilava / Typhlosion", "Turtwig / Grotle / Torterra", "Chimchar / Monferno / Infernape", "Tepig / Pignite / Emboar", "Rowlet / Dartrix / Decidueye", "Popplio / Brionne / Primarina"] }
  ]},
  { heading: "h2", text: "3. Candidates & New DLC Megas (93)", subsections: [
      { heading: "h3", text: "Hoenn Starters & Kanto/Johto Megas", lines: ["Treecko / Grovyle / Sceptile", "Torchic / Combusken / Blaziken", "Mudkip / Marshtomp / Swampert", "Weedle / Kakuna / Beedrill", "Pidgey / Pidgeotto / Pidgeot", "Abra / Kadabra / Alakazam", "Slowpoke / Slowbro", "Aerodactyl", "Mareep / Flaaffy / Ampharos", "Onix / Steelix", "Houndour / Houndoom", "Bellsprout / Weepinbell / Victreebel"] },
      { heading: "h3", text: "Hoenn, Sinnoh & Unova Megas", lines: ["Aron / Lairon / Aggron", "Meditite / Medicham", "Electrike / Manectric", "Carvanha / Sharpedo", "Numel / Camerupt", "Swablu / Altaria", "Shuppet / Banette", "Absol", "Snorunt / Glalie|Froslass", "Bagon / Shelgon / Salamence", "Mawile", "Sableye", "Buneary / Lopunny", "Snover / Abomasnow", "Audino", "Starly / Staravia / Staraptor"] },
      { heading: "h3", text: "New DLC Additions", lines: ["Skarmory", "Venipede / Whirlipede / Scolipede", "Skrelp / Dragalge", "Litleo / Pyroar", "Crabrawler / Crabominable", "Capsakid / Scovillain", "Golett / Golurk", "Drampa", "Tynamo / Eelektrik / Eelektross", "Falinks", "Binacle / Barbaracle", "Flabébé / Floette / Florges", "Chingling / Chimecho", "Espurr / Meowstic", "Indeedee", "Inkay / Malamar"] }
  ]},
  { heading: "h2", text: "4. VGC \"Glue\" & Weather Setters (37)", subsections: [
      { heading: null, text: null, lines: ["Foongus / Amoonguss", "Cleffa / Clefairy / Clefable", "Togepi / Togetic / Togekiss", "Impidimp / Morgrem / Grimmsnarl", "Wingull / Pelipper", "Torkoal", "Vulpix / Ninetales", "Porygon / Porygon2 / Porygon-Z", "Girafarig / Farigiraf", "Growlithe / Arcanine", "Mankey / Primeape / Annihilape", "Gimmighoul / Gholdengo", "Grookey / Thwackey / Rillaboom", "Scorbunny / Raboot / Cinderace", "Sobble / Drizzile / Inteleon"] }
  ]},
  { heading: "h2", text: "5. Regional Favorites & Type Balancing (70)", subsections: [
      { heading: null, text: null, lines: ["Sprigatito / Floragato / Meowscarada", "Fuecoco / Crocalor / Skeledirge", "Quaxly / Quaxwell / Quaquaval", "Charcadet / Armarouge|Ceruledge", "Paldean Wooper / Clodsire", "Nacli / Naclstack / Garganacl", "Frigibax / Arctibax / Baxcalibur", "Applin / Flapple|Appletun|Dipplin / Hydrapple", "Munchlax / Snorlax", "Lapras", "Ditto", "Rotom", "Magnemite / Magneton / Magnezone", "Azurill / Marill / Azumarill", "Koffing / Weezing", "Grimer / Muk", "Zorua / Zoroark", "Wimpod / Golisopod", "Dewpider / Araquanid", "Mimikyu", "Shroomish / Breloom", "Mareanie / Toxapex", "Rookidee / Corvisquire / Corviknight", "Shellos / Gastrodon", "Drilbur / Excadrill", "Glimmet / Glimmora", "Flamigo", "Smeargle", "Bronzor / Bronzong", "Makuhita / Hariyama", "Scraggy / Scrafty", "Vullaby / Mandibuzz", "Rufflet / Braviary", "Gothita / Gothorita / Gothitelle", "Litwick / Lampent / Chandelure"] }
  ]},
  { heading: "h2", text: "6. Regional Variants (Alola, Galar, Hisui, Paldea)", subsections: [
      { heading: null, text: null, lines: ["Alolan Raichu", "Alolan Sandshrew / Alolan Sandslash", "Alolan Vulpix / Alolan Ninetales", "Alolan Grimer / Alolan Muk", "Galarian Slowpoke / Galarian Slowbro", "Galarian Weezing", "Hisuian Growlithe / Hisuian Arcanine", "Hisuian Typhlosion", "Hisuian Samurott", "Hisuian Zorua / Hisuian Zoroark", "Hisuian Braviary", "Hisuian Decidueye"] }
  ]},
  { heading: "h2", text: "7. VGC Legends & Top Cut (21)", subsections: [
      { heading: null, text: null, lines: ["Hitmontop / Pachirisu", "Groudon / Kyogre / Rayquaza", "Heatran / Cresselia", "Thundurus / Landorus-Therian", "Tapu Koko / Tapu Fini / Kartana", "Zacian-Crowned / Calyrex-Ice / Calyrex-Shadow", "Urshifu-Rapid-Strike", "Flutter Mane / Iron Hands / Raging Bolt", "Chien-Pao / Ogerpon-Hearthflame"] }
  ]}
];

const TOP_CUT_TEAMS = {
    "worlds2024": `Calyrex-Ice @ Clear Amulet\nAbility: As One (Glastrier)\nLevel: 50\nTera Type: Grass\n- Glacial Lance\n- High Horsepower\n- Trick Room\n- Protect\n\nUrshifu-Rapid-Strike @ Focus Sash\nAbility: Unseen Fist\nLevel: 50\nTera Type: Water\n- Surging Strikes\n- Close Combat\n- Aqua Jet\n- Protect\n\nAmoonguss @ Rocky Helmet\nAbility: Regenerator\nLevel: 50\nTera Type: Water\n- Spore\n- Pollen Puff\n- Rage Powder\n- Protect\n\nIncineroar @ Safety Goggles\nAbility: Intimidate\nLevel: 50\nTera Type: Ghost\n- Flare Blitz\n- Knock Off\n- Parting Shot\n- Fake Out\n\nRaging Bolt @ Assault Vest\nAbility: Protosynthesis\nLevel: 50\nTera Type: Fairy\n- Electro Shot\n- Draco Meteor\n- Thunderbolt\n- Snarl\n\nOgerpon-Hearthflame @ Hearthflame Mask\nAbility: Mold Breaker\nLevel: 50\nTera Type: Fire\n- Ivy Cudgel\n- Horn Leech\n- Spiky Shield\n- Follow Me`,
    "naic2024": `Calyrex-Ice @ Clear Amulet\nAbility: As One (Glastrier)\nLevel: 50\nTera Type: Water\n- Glacial Lance\n- High Horsepower\n- Trick Room\n- Protect\n\nAmoonguss @ Rocky Helmet\nAbility: Regenerator\nLevel: 50\nTera Type: Water\n- Spore\n- Sludge Bomb\n- Rage Powder\n- Protect\n\nPelipper @ Focus Sash\nAbility: Drizzle\nLevel: 50\nTera Type: Ghost\n- Weather Ball\n- Hurricane\n- Tailwind\n- Wide Guard\n\nUrshifu-Rapid-Strike @ Choice Scarf\nAbility: Unseen Fist\nLevel: 50\nTera Type: Water\n- Surging Strikes\n- Close Combat\n- U-turn\n- Aqua Jet\n\nIncineroar @ Sitrus Berry\nAbility: Intimidate\nLevel: 50\nTera Type: Grass\n- Flare Blitz\n- Knock Off\n- Parting Shot\n- Fake Out\n\nRaging Bolt @ Assault Vest\nAbility: Protosynthesis\nLevel: 50\nTera Type: Bug\n- Electro Shot\n- Dragon Pulse\n- Thunderbolt\n- Snarl`,
    "worlds2023": `Amoonguss @ Sitrus Berry\nAbility: Regenerator\nLevel: 50\nTera Type: Water\n- Spore\n- Pollen Puff\n- Rage Powder\n- Protect\n\nFlutter Mane @ Booster Energy\nAbility: Protosynthesis\nLevel: 50\nTera Type: Fairy\n- Dazzling Gleam\n- Shadow Ball\n- Moonblast\n- Protect\n\nIron Hands @ Assault Vest\nAbility: Quark Drive\nLevel: 50\nTera Type: Water\n- Drain Punch\n- Wild Charge\n- Heavy Slam\n- Fake Out\n\nLandorus-Therian @ Choice Scarf\nAbility: Intimidate\nLevel: 50\nTera Type: Flying\n- Stomping Tantrum\n- Tera Blast\n- U-turn\n- Rock Slide\n\nChien-Pao @ Focus Sash\nAbility: Sword of Ruin\nLevel: 50\nTera Type: Ghost\n- Icicle Crash\n- Sucker Punch\n- Sacred Sword\n- Protect\n\nUrshifu-Rapid-Strike @ Mystic Water\nAbility: Unseen Fist\nLevel: 50\nTera Type: Water\n- Surging Strikes\n- Close Combat\n- Aqua Jet\n- Protect`,
    "worlds2022": `Gastrodon @ Leftovers\nAbility: Storm Drain\nLevel: 50\n- Earth Power\n- Icy Wind\n- Yawn\n- Protect\n\nCalyrex-Shadow @ Focus Sash\nAbility: As One (Spectrier)\nLevel: 50\n- Astral Barrage\n- Snarl\n- Will-O-Wisp\n- Protect\n\nRillaboom @ Assault Vest\nAbility: Grassy Surge\nLevel: 50\n- Grassy Glide\n- Fake Out\n- Knock Off\n- High Horsepower\n\nIncineroar @ Shuca Berry\nAbility: Intimidate\nLevel: 50\n- Flare Blitz\n- Parting Shot\n- Fake Out\n- Throat Chop\n\nThundurus @ Life Orb\nAbility: Defiant\nLevel: 50\n- Wild Charge\n- Taunt\n- Fly\n- Protect\n\nZacian-Crowned @ Rusted Sword\nAbility: Intrepid Sword\nLevel: 50\n- Iron Head\n- Sacred Sword\n- Substitute\n- Protect`,
    "worlds2019": `Groudon @ Aguav Berry\nAbility: Drought\nLevel: 50\n- Precipice Blades\n- Fire Punch\n- Swords Dance\n- Protect\n\nKyogre @ Blue Orb\nAbility: Drizzle\nLevel: 50\n- Water Spout\n- Origin Pulse\n- Ice Beam\n- Protect\n\nSalamence-Mega @ Salamencite\nAbility: Aerilate\nLevel: 50\n- Double-Edge\n- Tailwind\n- Roar\n- Protect\n\nIncineroar @ Incinium Z\nAbility: Intimidate\nLevel: 50\n- Flare Blitz\n- Darkest Lariat\n- U-turn\n- Fake Out\n\nTapu Fini @ Iapapa Berry\nAbility: Misty Surge\nLevel: 50\n- Moonblast\n- Icy Wind\n- Nature's Madness\n- Protect\n\nAmoonguss @ Focus Sash\nAbility: Regenerator\nLevel: 50\n- Clear Smog\n- Spore\n- Rage Powder\n- Protect`,
    "worlds2018": `Incineroar @ Figy Berry\nAbility: Intimidate\nLevel: 50\n- Flare Blitz\n- Knock Off\n- U-turn\n- Fake Out\n\nGastrodon @ Iapapa Berry\nAbility: Storm Drain\nLevel: 50\n- Earth Power\n- Ice Beam\n- Recover\n- Protect\n\nSalamence-Mega @ Salamencite\nAbility: Aerilate\nLevel: 50\n- Hyper Voice\n- Tailwind\n- Roar\n- Protect\n\nTapu Koko @ Electrium Z\nAbility: Electric Surge\nLevel: 50\n- Thunderbolt\n- Volt Switch\n- Nature's Madness\n- Protect\n\nSnorlax @ Mago Berry\nAbility: Gluttony\nLevel: 50\n- Return\n- High Horsepower\n- Belly Drum\n- Recycle\n\nKartana @ Assault Vest\nAbility: Beast Boost\nLevel: 50\n- Leaf Blade\n- Sacred Sword\n- Knock Off\n- Smart Strike`,
    "worlds2016": `Rayquaza @ Focus Sash\nAbility: Air Lock\nLevel: 50\n- Dragon Ascent\n- Extreme Speed\n- Swords Dance\n- Protect\n\nKyogre @ Blue Orb\nAbility: Drizzle\nLevel: 50\n- Water Spout\n- Origin Pulse\n- Ice Beam\n- Protect\n\nGengar-Mega @ Gengarite\nAbility: Levitate\nLevel: 50\n- Sludge Bomb\n- Will-O-Wisp\n- Trick Room\n- Protect\n\nHitmontop @ Eject Button\nAbility: Intimidate\nLevel: 50\n- Fake Out\n- Close Combat\n- Feint\n- Wide Guard\n\nRaichu @ Assault Vest\nAbility: Lightning Rod\nLevel: 50\n- Fake Out\n- Volt Switch\n- Endeavor\n- Nuzzle\n\nBronzong @ Mental Herb\nAbility: Levitate\nLevel: 50\n- Gyro Ball\n- Trick Room\n- Skill Swap\n- Hypnosis`,
    "worlds2015": `Kangaskhan-Mega @ Kangaskhanite\nAbility: Scrappy\nLevel: 50\n- Return\n- Low Kick\n- Sucker Punch\n- Fake Out\n\nHeatran @ Shuca Berry\nAbility: Flash Fire\nLevel: 50\n- Heat Wave\n- Earth Power\n- Substitute\n- Protect\n\nThundurus @ Safety Goggles\nAbility: Prankster\nLevel: 50\n- Thunderbolt\n- Thunder Wave\n- Swagger\n- Protect\n\nLandorus-Therian @ Choice Scarf\nAbility: Intimidate\nLevel: 50\n- Earthquake\n- Rock Slide\n- Superpower\n- Knock Off\n\nCresselia @ Rocky Helmet\nAbility: Levitate\nLevel: 50\n- Psychic\n- Ice Beam\n- Trick Room\n- Protect\n\nAmoonguss @ Rocky Helmet\nAbility: Regenerator\nLevel: 50\n- Spore\n- Rage Powder\n- Energy Ball\n- Sunny Day`,
    "worlds2014": `Pachirisu @ Sitrus Berry\nAbility: Volt Absorb\nLevel: 50\n- Nuzzle\n- Follow Me\n- Super Fang\n- Protect\n\nGothitelle @ Leftovers\nAbility: Shadow Tag\nLevel: 50\n- Psyshock\n- Thunder Wave\n- Tickle\n- Protect\n\nGardevoir @ Choice Scarf\nAbility: Telepathy\nLevel: 50\n- Dazzling Gleam\n- Psychic\n- Moonblast\n- Swagger\n\nGyarados-Mega @ Gyaradosite\nAbility: Intimidate\nLevel: 50\n- Dragon Dance\n- Waterfall\n- Earthquake\n- Protect\n\nTalonflame @ Life Orb\nAbility: Gale Wings\nLevel: 50\n- Brave Bird\n- Overheat\n- Taunt\n- Quick Guard\n\nGarchomp @ Focus Sash\nAbility: Rough Skin\nLevel: 50\n- Earthquake\n- Dragon Claw\n- Rock Slide\n- Protect`
};

const TYPE_DATA = {
  Normal: { weakTo: ['Fighting'], resists: [], immuneTo: ['Ghost'] },
  Fire: { weakTo: ['Water', 'Ground', 'Rock'], resists: ['Fire', 'Grass', 'Ice', 'Bug', 'Steel', 'Fairy'], immuneTo: [] },
  Water: { weakTo: ['Electric', 'Grass'], resists: ['Fire', 'Water', 'Ice', 'Steel'], immuneTo: [] },
  Electric: { weakTo: ['Ground'], resists: ['Electric', 'Flying', 'Steel'], immuneTo: [] },
  Grass: { weakTo: ['Fire', 'Ice', 'Poison', 'Flying', 'Bug'], resists: ['Water', 'Electric', 'Grass', 'Ground'], immuneTo: [] },
  Ice: { weakTo: ['Fire', 'Fighting', 'Rock', 'Steel'], resists: ['Ice'], immuneTo: [] },
  Fighting: { weakTo: ['Flying', 'Psychic', 'Fairy'], resists: ['Bug', 'Rock', 'Dark'], immuneTo: [] },
  Poison: { weakTo: ['Ground', 'Psychic'], resists: ['Grass', 'Fighting', 'Poison', 'Bug', 'Fairy'], immuneTo: [] },
  Ground: { weakTo: ['Water', 'Grass', 'Ice'], resists: ['Poison', 'Rock'], immuneTo: ['Electric'] },
  Flying: { weakTo: ['Electric', 'Ice', 'Rock'], resists: ['Grass', 'Fighting', 'Bug'], immuneTo: ['Ground'] },
  Psychic: { weakTo: ['Bug', 'Ghost', 'Dark'], resists: ['Fighting', 'Psychic'], immuneTo: [] },
  Bug: { weakTo: ['Fire', 'Flying', 'Rock'], resists: ['Grass', 'Fighting', 'Ground'], immuneTo: [] },
  Rock: { weakTo: ['Water', 'Grass', 'Fighting', 'Ground', 'Steel'], resists: ['Normal', 'Fire', 'Poison', 'Flying'], immuneTo: [] },
  Ghost: { weakTo: ['Ghost', 'Dark'], resists: ['Poison', 'Bug'], immuneTo: ['Normal', 'Fighting'] },
  Dragon: { weakTo: ['Ice', 'Dragon', 'Fairy'], resists: ['Fire', 'Water', 'Electric', 'Grass'], immuneTo: [] },
  Dark: { weakTo: ['Fighting', 'Bug', 'Fairy'], resists: ['Ghost', 'Dark'], immuneTo: ['Psychic'] },
  Steel: { weakTo: ['Fire', 'Fighting', 'Ground'], resists: ['Normal', 'Grass', 'Ice', 'Flying', 'Psychic', 'Bug', 'Rock', 'Dragon', 'Steel', 'Fairy'], immuneTo: ['Poison'] },
  Fairy: { weakTo: ['Poison', 'Steel'], resists: ['Fighting', 'Bug', 'Dark'], immuneTo: ['Dragon'] }
};

const TYPE_COLORS = {
  Normal: '#A8A878', Fire: '#F08030', Water: '#6890F0', Electric: '#F8D030', Grass: '#78C850', Ice: '#98D8D8',
  Fighting: '#C03028', Poison: '#A040A0', Ground: '#E0C068', Flying: '#A890F0', Psychic: '#F85888', Bug: '#A8B820',
  Rock: '#B8A038', Ghost: '#705898', Dragon: '#7038F8', Dark: '#705848', Steel: '#B8B8D0', Fairy: '#EE99AC'
};

const MEGA_MAP = {
  "abomasnow": [{ stone: "Abomasite", id: "abomasnowmega" }], "absol": [{ stone: "Absolite", id: "absolmega" }, { stone: "Absolite Z", id: "absolmegaz" }],
  "aerodactyl": [{ stone: "Aerodactylite", id: "aerodactylmega" }], "aggron": [{ stone: "Aggronite", id: "aggronmega" }],
  "alakazam": [{ stone: "Alakazite", id: "alakazammega" }], "altaria": [{ stone: "Altarianite", id: "altariamega" }],
  "ampharos": [{ stone: "Ampharosite", id: "ampharosmega" }], "audino": [{ stone: "Audinite", id: "audinomega" }],
  "banette": [{ stone: "Banettite", id: "banettemega" }], "barbaracle": [{ stone: "Barbaracite", id: "barbaraclemega" }],
  "baxcalibur": [{ stone: "Baxcalibrite", id: "baxcaliburmega" }], "beedrill": [{ stone: "Beedrillite", id: "beedrillmega" }],
  "blastoise": [{ stone: "Blastoisinite", id: "blastoisemega" }], "blaziken": [{ stone: "Blazikenite", id: "blazikenmega" }],
  "camerupt": [{ stone: "Cameruptite", id: "cameruptmega" }], "chandelure": [{ stone: "Chandelurite", id: "chandeluremega" }],
  "charizard": [{ stone: "Charizardite X", id: "charizardmegax" }, { stone: "Charizardite Y", id: "charizardmegay" }],
  "chesnaught": [{ stone: "Chesnaughtite", id: "chesnaughtmega" }], "chimecho": [{ stone: "Chimechite", id: "chimechomega" }],
  "clefable": [{ stone: "Clefablite", id: "clefablemega" }], "crabominable": [{ stone: "Crabominite", id: "crabominablemega" }],
  "delphox": [{ stone: "Delphoxite", id: "delphoxmega" }], "dragalge": [{ stone: "Dragalgite", id: "dragalgemega" }],
  "dragonite": [{ stone: "Dragoninite", id: "dragonitemega" }], "drampa": [{ stone: "Drampanite", id: "drampamega" }],
  "eelektross": [{ stone: "Eelektrossite", id: "eelektrossmega" }], "emboar": [{ stone: "Emboarite", id: "emboarmega" }],
  "excadrill": [{ stone: "Excadrite", id: "excadrillmega" }], "falinks": [{ stone: "Falinksite", id: "falinksmega" }],
  "feraligatr": [{ stone: "Feraligite", id: "feraligatrmega" }], "floette": [{ stone: "Floettite", id: "floettemega" }], 
  "froslass": [{ stone: "Froslassite", id: "froslassmega" }], "gallade": [{ stone: "Galladite", id: "gallademega" }],
  "garchomp": [{ stone: "Garchompite", id: "garchompmega" }], "gardevoir": [{ stone: "Gardevoirite", id: "gardevoirmega" }],
  "gengar": [{ stone: "Gengarite", id: "gengarmega" }], "glalie": [{ stone: "Glalitite", id: "glaliemega" }],
  "glimmora": [{ stone: "Glimmoranite", id: "glimmoramega" }], "golisopod": [{ stone: "Golisopite", id: "golisopodmega" }],
  "golurk": [{ stone: "Golurkite", id: "golurkmega" }], "greninja": [{ stone: "Greninjite", id: "greninjamega" }],
  "gyarados": [{ stone: "Gyaradosite", id: "gyaradosmega" }], "hawlucha": [{ stone: "Hawluchanite", id: "hawluchamega" }],
  "heracross": [{ stone: "Heracronite", id: "heracrossmega" }], "houndoom": [{ stone: "Houndoominite", id: "houndoommega" }],
  "kangaskhan": [{ stone: "Kangaskhanite", id: "kangaskhanmega" }], "lopunny": [{ stone: "Lopunnite", id: "lopunnymega" }],
  "lucario": [{ stone: "Lucarionite", id: "lucariomega" }, { stone: "Lucarionite Z", id: "lucariomegaz" }],
  "malamar": [{ stone: "Malamarite", id: "malamarmega" }], "manectric": [{ stone: "Manectite", id: "manectricmega" }],
  "mawile": [{ stone: "Mawilite", id: "mawilemega" }], "medicham": [{ stone: "Medichamite", id: "medichammega" }],
  "meganium": [{ stone: "Meganiumite", id: "meganiummega" }], "meowstic": [{ stone: "Meowsticite", id: "meowsticmega" }],
  "metagross": [{ stone: "Metagrossite", id: "metagrossmega" }], "pidgeot": [{ stone: "Pidgeotite", id: "pidgeotmega" }],
  "pinsir": [{ stone: "Pinsirite", id: "pinsirmega" }], "pyroar": [{ stone: "Pyroarite", id: "pyroarmega" }],
  "raichu": [{ stone: "Raichunite X", id: "raichumegax" }, { stone: "Raichunite Y", id: "raichumegay" }],
  "sableye": [{ stone: "Sablenite", id: "sableyemega" }], "salamence": [{ stone: "Salamencite", id: "salamencemega" }],
  "sceptile": [{ stone: "Sceptilite", id: "sceptilemega" }], "scizor": [{ stone: "Scizorite", id: "scizormega" }],
  "scolipede": [{ stone: "Scolipite", id: "scolipedemega" }], "scovillain": [{ stone: "Scovillainite", id: "scovillainmega" }],
  "scrafty": [{ stone: "Scraftinite", id: "scraftymega" }], "sharpedo": [{ stone: "Sharpedonite", id: "sharpedomega" }],
  "skarmory": [{ stone: "Skarmorite", id: "skarmorymega" }], "slowbro": [{ stone: "Slowbronite", id: "slowbromega" }],
  "staraptor": [{ stone: "Staraptite", id: "staraptormega" }], "starmie": [{ stone: "Starminite", id: "starmiemega" }],
  "steelix": [{ stone: "Steelixite", id: "steelixmega" }], "swampert": [{ stone: "Swampertite", id: "swampertmega" }],
  "tyranitar": [{ stone: "Tyranitarite", id: "tyranitarmega" }], "venusaur": [{ stone: "Venusaurite", id: "venusaurmega" }],
  "victreebel": [{ stone: "Victreebelite", id: "victreebelmega" }], "aegislash": [{ stone: "Blade Form", id: "aegislashblade" }],
  "indeedee": [{ stone: "Female Form", id: "indeedeef" }], "palafin": [{ stone: "Hero Form", id: "palafinhero" }],
  "rotom": [
      { stone: "Wash Rotom", id: "rotomwash" }, { stone: "Heat Rotom", id: "rotomheat" },
      { stone: "Mow Rotom", id: "rotommow" }, { stone: "Frost Rotom", id: "rotomfrost" }, { stone: "Fan Rotom", id: "rotomfan" }
  ],
  "tatsugiri": [
      { stone: "Droopy Form", id: "tatsugiridroopy" }, { stone: "Stretchy Form", id: "tatsugiristretchy" }, { stone: "Curly Form", id: "tatsugiricurly" }
  ],
  "gastrodon": [
    { stone: "West Sea (Pink)", id: "gastrodon" },
    { stone: "East Sea (Blue)", id: "gastrodoneast" }
  ]
};

const ABILITY_DEFENSES = {
  "Levitate": { immuneTo: ["Ground"] }, "Earth Eater": { immuneTo: ["Ground"] }, "Water Absorb": { immuneTo: ["Water"] },
  "Storm Drain": { immuneTo: ["Water"] }, "Dry Skin": { immuneTo: ["Water"], weakTo: ["Fire"] }, "Volt Absorb": { immuneTo: ["Electric"] },
  "Motor Drive": { immuneTo: ["Electric"] }, "Lightning Rod": { immuneTo: ["Electric"] }, "Flash Fire": { immuneTo: ["Fire"] },
  "Well-Baked Body": { immuneTo: ["Fire"] }, "Sap Sipper": { immuneTo: ["Grass"] }, "Thick Fat": { resists: ["Fire", "Ice"] },
  "Purifying Salt": { resists: ["Ghost"] }, "Heatproof": { resists: ["Fire"] }, "Water Bubble": { resists: ["Fire"] }
};

const CUSTOM_SPRITES = {
  "raichumegax": "images/raichu-mega-x.png", "raichumegay": "images/raichu-mega-y.png", "clefablemega": "images/clefable-mega.png",
  "victreebelmega": "images/victreebel-mega.png", "starmiemega": "images/starmie-mega.png", "dragonitemega": "images/dragonite-mega.png",
  "meganiummega": "images/meganium-mega.png", "feraligatrmega": "images/feraligatr-mega.png", "skarmorymega": "images/skarmory-mega.png",
  "chimechomega": "images/chimecho-mega.png", "absolmegaz": "images/absol-mega-z.png", "staraptormega": "images/staraptor-mega.png",
  "froslassmega": "images/froslass-mega.png", "emboarmega": "images/emboar-mega.png", "excadrillmega": "images/excadrill-mega.png",
  "scolipedemega": "images/scolipede-mega.png", "scraftymega": "images/scrafty-mega.png", "eelektrossmega": "images/eelektross-mega.png", 
  "chandeluremega": "images/chandelure-mega.png", "golurkmega": "images/golurk-mega.png", "chesnaughtmega": "images/chesnaught-mega.png",
  "delphoxmega": "images/delphox-mega.png", "greninjamega": "images/greninja-mega.png", "pyroarmega": "images/pyroar-mega.png",
  "floettemega": "images/floette-mega.png", "meowsticmega": "images/meowstic-mega.png", "malamarmega": "images/malamar-mega.png",
  "barbaraclemega": "images/barbaracle-mega.png", "dragalgemega": "images/dragalge-mega.png", "hawluchamega": "images/hawlucha-mega.png",
  "crabominablemega": "images/crabominable-mega.png", "golisopodmega": "images/golisopod-mega.png", "drampamega": "images/drampa-mega.png",
  "falinksmega": "images/falinks-mega.png", "scovillainmega": "images/scovillain-mega.png", "glimmoramega": "images/glimmora-mega.png",
  "tatsugirimegadroopy": "images/tatsugiri-mega-droopy.png", "tatsugirimegastretchy": "images/tatsugiri-mega-stretchy.png",
  "tatsugirimegacurly": "images/tatsugiri-mega-curly.png", "baxcaliburmega": "images/baxcalibur-mega.png", "lucariomegaz": "images/lucario-mega-z.png",
  "indeedeef": "https://play.pokemonshowdown.com/sprites/gen5/indeedee-f.png", "aegislashblade": "https://play.pokemonshowdown.com/sprites/gen5/aegislash-blade.png",
  "palafinhero": "https://play.pokemonshowdown.com/sprites/gen5/palafin-hero.png", "rotomwash": "https://play.pokemonshowdown.com/sprites/gen5/rotom-wash.png",
  "rotomheat": "https://play.pokemonshowdown.com/sprites/gen5/rotom-heat.png", "rotommow": "https://play.pokemonshowdown.com/sprites/gen5/rotom-mow.png",
  "rotomfrost": "https://play.pokemonshowdown.com/sprites/gen5/rotom-frost.png", "rotomfan": "https://play.pokemonshowdown.com/sprites/gen5/rotom-fan.png"
};

const TERA_TYPES = ['Normal', 'Fire', 'Water', 'Electric', 'Grass', 'Ice', 'Fighting', 'Poison', 'Ground', 'Flying', 'Psychic', 'Bug', 'Rock', 'Ghost', 'Dragon', 'Dark', 'Steel', 'Fairy', 'Stellar'];

const POKEMON_AESTHETICS = {
  "bulbasaur": { letter: "B", color: "#78C850" }, "ivysaur": { letter: "I", color: "#78C850" }, "venusaur": { letter: "V", color: "#78C850" },
  "charmander": { letter: "C", color: "#F08030" }, "charmeleon": { letter: "C", color: "#F08030" }, "charizard": { letter: "C", color: "#F08030" },
  "squirtle": { letter: "S", color: "#6890F0" }, "wartortle": { letter: "W", color: "#6890F0" }, "blastoise": { letter: "B", color: "#6890F0" },
  "pichu": { letter: "P", color: "#F8D030" }, "pikachu": { letter: "P", color: "#F8D030" }, "raichu": { letter: "R", color: "#F8D030" },
  "gastrodoneast": { letter: "G", color: "#6890F0" },
  "gastly": { letter: "G", color: "#705898" }, "haunter": { letter: "H", color: "#705898" }, "gengar": { letter: "G", color: "#705898" },
  "kangaskhan": { letter: "K", color: "#A8A878" }, "staryu": { letter: "S", color: "#6890F0" }, "starmie": { letter: "S", color: "#F85888" },
  "pinsir": { letter: "P", color: "#A8B820" }, "magikarp": { letter: "M", color: "#F08030" }, "gyarados": { letter: "G", color: "#6890F0" },
  "dratini": { letter: "D", color: "#7038F8" }, "dragonair": { letter: "D", color: "#7038F8" }, "dragonite": { letter: "D", color: "#F08030" },
  "totodile": { letter: "T", color: "#6890F0" }, "croconaw": { letter: "C", color: "#6890F0" }, "feraligatr": { letter: "F", color: "#6890F0" },
  "scyther": { letter: "S", color: "#A8B820" }, "scizor": { letter: "S", color: "#C03028" }, "heracross": { letter: "H", color: "#C03028" },
  "larvitar": { letter: "L", color: "#B8A038" }, "pupitar": { letter: "P", color: "#B8A038" }, "tyranitar": { letter: "T", color: "#705848" },
  "ralts": { letter: "R", color: "#F85888" }, "kirlia": { letter: "K", color: "#F85888" }, "gardevoir": { letter: "G", color: "#F85888" }, "gallade": { letter: "G", color: "#C03028" },
  "feebas": { letter: "F", color: "#A8A878" }, "milotic": { letter: "M", color: "#6890F0" }, "beldum": { letter: "B", color: "#B8B8D0" },
  "metang": { letter: "M", color: "#B8B8D0" }, "metagross": { letter: "M", color: "#B8B8D0" }, "piplup": { letter: "P", color: "#6890F0" },
  "prinplup": { letter: "P", color: "#6890F0" }, "empoleon": { letter: "E", color: "#B8B8D0" }, "gible": { letter: "G", color: "#7038F8" },
  "gabite": { letter: "G", color: "#7038F8" }, "garchomp": { letter: "G", color: "#7038F8" }, "riolu": { letter: "R", color: "#C03028" }, "lucario": { letter: "L", color: "#B8B8D0" },
  "snivy": { letter: "S", color: "#78C850" }, "servine": { letter: "S", color: "#78C850" }, "serperior": { letter: "S", color: "#78C850" },
  "oshawott": { letter: "O", color: "#6890F0" }, "dewott": { letter: "D", color: "#6890F0" }, "samurott": { letter: "S", color: "#6890F0" },
  "cottonee": { letter: "C", color: "#78C850" }, "whimsicott": { letter: "W", color: "#EE99AC" }, "emolga": { letter: "E", color: "#F8D030" },
  "deino": { letter: "D", color: "#705848" }, "zweilous": { letter: "Z", color: "#705848" }, "hydreigon": { letter: "H", color: "#705848" },
  "chespin": { letter: "C", color: "#78C850" }, "quilladin": { letter: "Q", color: "#78C850" }, "chesnaught": { letter: "C", color: "#78C850" },
  "fennekin": { letter: "F", color: "#F08030" }, "braixen": { letter: "B", color: "#F08030" }, "delphox": { letter: "D", color: "#F85888" },
  "froakie": { letter: "F", color: "#6890F0" }, "frogadier": { letter: "F", color: "#6890F0" }, "greninja": { letter: "G", color: "#705848" },
  "fletchling": { letter: "F", color: "#A8A878" }, "fletchinder": { letter: "F", color: "#F08030" }, "talonflame": { letter: "T", color: "#F08030" },
  "honedge": { letter: "H", color: "#B8B8D0" }, "doublade": { letter: "D", color: "#B8B8D0" }, "aegislash": { letter: "A", color: "#B8B8D0" }, "hawlucha": { letter: "H", color: "#C03028" },
  "litten": { letter: "L", color: "#F08030" }, "torracat": { letter: "T", color: "#F08030" }, "incineroar": { letter: "I", color: "#705848" },
  "bounsweet": { letter: "B", color: "#78C850" }, "steenee": { letter: "S", color: "#78C850" }, "tsareena": { letter: "T", color: "#78C850" },
  "oranguru": { letter: "O", color: "#A8A878" }, "jangmoo": { letter: "J", color: "#7038F8" }, "hakamoo": { letter: "H", color: "#7038F8" }, "kommoo": { letter: "K", color: "#7038F8" },
  "hatenna": { letter: "H", color: "#F85888" }, "hattrem": { letter: "H", color: "#F85888" }, "hatterene": { letter: "H", color: "#EE99AC" },
  "dreepy": { letter: "D", color: "#705898" }, "drakloak": { letter: "D", color: "#705898" }, "dragapult": { letter: "D", color: "#705898" },
  "teddiursa": { letter: "T", color: "#A8A878" }, "ursaring": { letter: "U", color: "#A8A878" }, "ursaluna": { letter: "U", color: "#E0C068" },
  "basculin": { letter: "B", color: "#6890F0" }, "basculegion": { letter: "B", color: "#705898" }, "sneaselhisui": { letter: "H", color: "#C03028" }, "sneasler": { letter: "S", color: "#C03028" },
  "tandemaus": { letter: "T", color: "#A8A878" }, "maushold": { letter: "M", color: "#A8A878" }, "tinkatink": { letter: "T", color: "#EE99AC" },
  "tinkatuff": { letter: "T", color: "#EE99AC" }, "tinkaton": { letter: "T", color: "#EE99AC" }, "finizen": { letter: "F", color: "#6890F0" }, "palafin": { letter: "P", color: "#6890F0" },
  "dondozo": { letter: "D", color: "#6890F0" }, "tatsugiri": { letter: "T", color: "#7038F8" }, "pawniard": { letter: "P", color: "#705848" },
  "bisharp": { letter: "B", color: "#705848" }, "kingambit": { letter: "K", color: "#705848" }, "poltchageist": { letter: "P", color: "#78C850" },
  "sinistcha": { letter: "S", color: "#78C850" }, "duraludon": { letter: "D", color: "#B8B8D0" }, "archaludon": { letter: "A", color: "#B8B8D0" },
  "eevee": { letter: "E", color: "#A8A878" }, "vaporeon": { letter: "V", color: "#6890F0" }, "jolteon": { letter: "J", color: "#F8D030" },
  "flareon": { letter: "F", color: "#F08030" }, "espeon": { letter: "E", color: "#F85888" }, "umbreon": { letter: "U", color: "#705848" },
  "leafeon": { letter: "L", color: "#78C850" }, "glaceon": { letter: "G", color: "#98D8D8" }, "sylveon": { letter: "S", color: "#EE99AC" },
  "chikorita": { letter: "C", color: "#78C850" }, "bayleef": { letter: "B", color: "#78C850" }, "meganium": { letter: "M", color: "#78C850" },
  "cyndaquil": { letter: "C", color: "#F08030" }, "quilava": { letter: "Q", color: "#F08030" }, "typhlosion": { letter: "T", color: "#F08030" },
  "turtwig": { letter: "T", color: "#78C850" }, "grotle": { letter: "G", color: "#78C850" }, "torterra": { letter: "T", color: "#78C850" },
  "chimchar": { letter: "C", color: "#F08030" }, "monferno": { letter: "M", color: "#F08030" }, "infernape": { letter: "I", color: "#F08030" },
  "tepig": { letter: "T", color: "#F08030" }, "pignite": { letter: "P", color: "#F08030" }, "emboar": { letter: "E", color: "#F08030" },
  "rowlet": { letter: "R", color: "#78C850" }, "dartrix": { letter: "D", color: "#78C850" }, "decidueye": { letter: "D", color: "#705898" },
  "popplio": { letter: "P", color: "#6890F0" }, "brionne": { letter: "B", color: "#6890F0" }, "primarina": { letter: "P", color: "#EE99AC" },
  "treecko": { letter: "T", color: "#78C850" }, "grovyle": { letter: "G", color: "#78C850" }, "sceptile": { letter: "S", color: "#78C850" },
  "torchic": { letter: "T", color: "#F08030" }, "combusken": { letter: "C", color: "#F08030" }, "blaziken": { letter: "B", color: "#F08030" },
  "mudkip": { letter: "M", color: "#6890F0" }, "marshtomp": { letter: "M", color: "#6890F0" }, "swampert": { letter: "S", color: "#6890F0" },
  "weedle": { letter: "W", color: "#A8B820" }, "kakuna": { letter: "K", color: "#A8B820" }, "beedrill": { letter: "B", color: "#A8B820" },
  "pidgey": { letter: "P", color: "#A8A878" }, "pidgeotto": { letter: "P", color: "#A8A878" }, "pidgeot": { letter: "P", color: "#A8A878" },
  "abra": { letter: "A", color: "#F85888" }, "kadabra": { letter: "K", color: "#F85888" }, "alakazam": { letter: "A", color: "#F85888" },
  "slowpoke": { letter: "S", color: "#6890F0" }, "slowbro": { letter: "S", color: "#6890F0" }, "aerodactyl": { letter: "A", color: "#B8A038" },
  "mareep": { letter: "M", color: "#F8D030" }, "flaaffy": { letter: "F", color: "#F8D030" }, "ampharos": { letter: "A", color: "#F8D030" },
  "onix": { letter: "O", color: "#B8A038" }, "steelix": { letter: "S", color: "#B8B8D0" }, "houndour": { letter: "H", color: "#705848" }, "houndoom": { letter: "H", color: "#705848" },
  "bellsprout": { letter: "B", color: "#78C850" }, "weepinbell": { letter: "W", color: "#78C850" }, "victreebel": { letter: "V", color: "#78C850" },
  "aron": { letter: "A", color: "#B8B8D0" }, "lairon": { letter: "L", color: "#B8B8D0" }, "aggron": { letter: "A", color: "#B8B8D0" },
  "meditite": { letter: "M", color: "#C03028" }, "medicham": { letter: "M", color: "#C03028" }, "electrike": { letter: "E", color: "#F8D030" },
  "manectric": { letter: "M", color: "#F8D030" }, "carvanha": { letter: "C", color: "#6890F0" }, "sharpedo": { letter: "S", color: "#6890F0" },
  "numel": { letter: "N", color: "#F08030" }, "camerupt": { letter: "C", color: "#F08030" }, "swablu": { letter: "S", color: "#A8A878" },
  "altaria": { letter: "A", color: "#7038F8" }, "shuppet": { letter: "S", color: "#705898" }, "banette": { letter: "B", color: "#705898" },
  "absol": { letter: "A", color: "#705848" }, "snorunt": { letter: "S", color: "#98D8D8" }, "glalie": { letter: "G", color: "#98D8D8" },
  "froslass": { letter: "F", color: "#705898" }, "bagon": { letter: "B", color: "#7038F8" }, "shelgon": { letter: "S", color: "#7038F8" },
  "salamence": { letter: "S", color: "#7038F8" }, "mawile": { letter: "M", color: "#B8B8D0" }, "sableye": { letter: "S", color: "#705848" },
  "buneary": { letter: "B", color: "#A8A878" }, "lopunny": { letter: "L", color: "#A8A878" }, "snover": { letter: "S", color: "#78C850" },
  "abomasnow": { letter: "A", color: "#98D8D8" }, "audino": { letter: "A", color: "#A8A878" }, "starly": { letter: "S", color: "#A8A878" },
  "staravia": { letter: "S", color: "#A8A878" }, "staraptor": { letter: "S", color: "#A8A878" }, "skarmory": { letter: "S", color: "#B8B8D0" },
  "venipede": { letter: "V", color: "#A8B820" }, "whirlipede": { letter: "W", color: "#A8B820" }, "scolipede": { letter: "S", color: "#A8B820" },
  "skrelp": { letter: "S", color: "#A040A0" }, "dragalge": { letter: "D", color: "#A040A0" }, "litleo": { letter: "L", color: "#F08030" },
  "pyroar": { letter: "P", color: "#F08030" }, "crabrawler": { letter: "C", color: "#C03028" }, "crabominable": { letter: "C", color: "#98D8D8" },
  "capsakid": { letter: "C", color: "#78C850" }, "scovillain": { letter: "S", color: "#78C850" }, "golett": { letter: "G", color: "#E0C068" },
  "golurk": { letter: "G", color: "#E0C068" }, "drampa": { letter: "D", color: "#A8A878" }, "tynamo": { letter: "T", color: "#F8D030" },
  "eelektrik": { letter: "E", color: "#F8D030" }, "eelektross": { letter: "E", color: "#F8D030" }, "falinks": { letter: "F", color: "#C03028" },
  "binacle": { letter: "B", color: "#B8A038" }, "barbaracle": { letter: "B", color: "#B8A038" }, "flabebe": { letter: "F", color: "#EE99AC" },
  "floette": { letter: "F", color: "#EE99AC" }, "florges": { letter: "F", color: "#EE99AC" }, "chingling": { letter: "C", color: "#F85888" },
  "chimecho": { letter: "C", color: "#F85888" }, "espurr": { letter: "E", color: "#F85888" }, "meowstic": { letter: "M", color: "#F85888" },
  "indeedee": { letter: "I", color: "#F85888" }, "inkay": { letter: "I", color: "#705848" }, "malamar": { letter: "M", color: "#705848" },
  "foongus": { letter: "F", color: "#78C850" }, "amoonguss": { letter: "A", color: "#78C850" }, "cleffa": { letter: "C", color: "#EE99AC" },
  "clefairy": { letter: "C", color: "#EE99AC" }, "clefable": { letter: "C", color: "#EE99AC" }, "togepi": { letter: "T", color: "#EE99AC" },
  "togetic": { letter: "T", color: "#EE99AC" }, "togekiss": { letter: "T", color: "#EE99AC" }, "impidimp": { letter: "I", color: "#705848" },
  "morgrem": { letter: "M", color: "#705848" }, "grimmsnarl": { letter: "G", color: "#705848" }, "wingull": { letter: "W", color: "#6890F0" },
  "pelipper": { letter: "P", color: "#6890F0" }, "torkoal": { letter: "T", color: "#F08030" }, "vulpix": { letter: "V", color: "#F08030" },
  "ninetales": { letter: "N", color: "#F08030" }, "porygon": { letter: "P", color: "#A8A878" }, "porygon2": { letter: "P", color: "#A8A878" },
  "porygonz": { letter: "P", color: "#A8A878" }, "girafarig": { letter: "G", color: "#A8A878" }, "farigiraf": { letter: "F", color: "#A8A878" },
  "growlithe": { letter: "G", color: "#F08030" }, "arcanine": { letter: "A", color: "#F08030" }, "mankey": { letter: "M", color: "#C03028" },
  "primeape": { letter: "P", color: "#C03028" }, "annihilape": { letter: "A", color: "#705898" }, "gimmighoul": { letter: "G", color: "#705898" },
  "gholdengo": { letter: "G", color: "#B8B8D0" }, "grookey": { letter: "G", color: "#78C850" }, "thwackey": { letter: "T", color: "#78C850" },
  "rillaboom": { letter: "R", color: "#78C850" }, "scorbunny": { letter: "S", color: "#F08030" }, "raboot": { letter: "R", color: "#F08030" },
  "cinderace": { letter: "C", color: "#F08030" }, "sobble": { letter: "S", color: "#6890F0" }, "drizzile": { letter: "D", color: "#6890F0" },
  "inteleon": { letter: "I", color: "#6890F0" }, "sprigatito": { letter: "S", color: "#78C850" }, "floragato": { letter: "F", color: "#78C850" },
  "meowscarada": { letter: "M", color: "#78C850" }, "fuecoco": { letter: "F", color: "#F08030" }, "crocalor": { letter: "C", color: "#F08030" },
  "skeledirge": { letter: "S", color: "#F08030" }, "quaxly": { letter: "Q", color: "#6890F0" }, "quaxwell": { letter: "Q", color: "#6890F0" },
  "quaquaval": { letter: "Q", color: "#6890F0" }, "charcadet": { letter: "C", color: "#F08030" }, "armarouge": { letter: "A", color: "#F08030" },
  "ceruledge": { letter: "C", color: "#F08030" }, "paldeanwooper": { letter: "P", color: "#A040A0" }, "clodsire": { letter: "C", color: "#A040A0" },
  "nacli": { letter: "N", color: "#B8A038" }, "naclstack": { letter: "N", color: "#B8A038" }, "garganacl": { letter: "G", color: "#B8A038" },
  "frigibax": { letter: "F", color: "#7038F8" }, "arctibax": { letter: "A", color: "#7038F8" }, "baxcalibur": { letter: "B", color: "#7038F8" },
  "applin": { letter: "A", color: "#78C850" }, "flapple": { letter: "F", color: "#78C850" }, "appletun": { letter: "A", color: "#78C850" },
  "dipplin": { letter: "D", color: "#78C850" }, "hydrapple": { letter: "H", color: "#78C850" }, "munchlax": { letter: "M", color: "#A8A878" },
  "snorlax": { letter: "S", color: "#A8A878" }, "lapras": { letter: "L", color: "#6890F0" }, "ditto": { letter: "D", color: "#A8A878" },
  "rotom": { letter: "R", color: "#F8D030" }, "magnemite": { letter: "M", color: "#F8D030" }, "magneton": { letter: "M", color: "#F8D030" },
  "magnezone": { letter: "M", color: "#F8D030" }, "azurill": { letter: "A", color: "#A8A878" }, "marill": { letter: "M", color: "#6890F0" },
  "azumarill": { letter: "A", color: "#6890F0" }, "koffing": { letter: "K", color: "#A040A0" }, "weezing": { letter: "W", color: "#A040A0" },
  "grimer": { letter: "G", color: "#A040A0" }, "muk": { letter: "M", color: "#A040A0" }, "zorua": { letter: "Z", color: "#705848" },
  "zoroark": { letter: "Z", color: "#705848" }, "wimpod": { letter: "W", color: "#A8B820" }, "golisopod": { letter: "G", color: "#A8B820" },
  "dewpider": { letter: "D", color: "#6890F0" }, "araquanid": { letter: "A", color: "#6890F0" }, "mimikyu": { letter: "M", color: "#705898" },
  "shroomish": { letter: "S", color: "#78C850" }, "breloom": { letter: "B", color: "#78C850" }, "mareanie": { letter: "M", color: "#A040A0" },
  "toxapex": { letter: "T", color: "#A040A0" }, "rookidee": { letter: "R", color: "#A8A878" }, "corvisquire": { letter: "C", color: "#A8A878" },
  "corviknight": { letter: "C", color: "#B8B8D0" }, "shellos": { letter: "S", color: "#6890F0" }, "gastrodon": { letter: "G", color: "#6890F0" },
  "drilbur": { letter: "D", color: "#E0C068" }, "excadrill": { letter: "E", color: "#E0C068" }, "glimmet": { letter: "G", color: "#B8A038" },
  "glimmora": { letter: "G", color: "#B8A038" }, "flamigo": { letter: "F", color: "#A8A878" }, "smeargle": { letter: "S", color: "#A8A878" },
  "bronzor": { letter: "B", color: "#B8B8D0" }, "bronzong": { letter: "B", color: "#B8B8D0" }, "makuhita": { letter: "M", color: "#C03028" },
  "hariyama": { letter: "H", color: "#C03028" }, "scraggy": { letter: "S", color: "#705848" }, "scrafty": { letter: "S", color: "#705848" },
  "vullaby": { letter: "V", color: "#705848" }, "mandibuzz": { letter: "M", color: "#705848" }, "rufflet": { letter: "R", color: "#A8A878" },
  "braviary": { letter: "B", color: "#A8A878" }, "gothita": { letter: "G", color: "#F85888" }, "gothorita": { letter: "G", color: "#F85888" },
  "gothitelle": { letter: "G", color: "#F85888" }, "litwick": { letter: "L", color: "#705898" }, "lampent": { letter: "L", color: "#705898" },
  "chandelure": { letter: "C", color: "#705898" }, "raichualola": { letter: "A", color: "#F8D030" }, "sandshrewalola": { letter: "A", color: "#98D8D8" },
  "sandslashalola": { letter: "A", color: "#98D8D8" }, "vulpixalola": { letter: "A", color: "#98D8D8" }, "ninetalesalola": { letter: "A", color: "#98D8D8" },
  "grimeralola": { letter: "A", color: "#A040A0" }, "mukalola": { letter: "A", color: "#A040A0" }, "slowpokegalar": { letter: "G", color: "#F85888" },
  "slowbrogalar": { letter: "G", color: "#A040A0" }, "weezinggalar": { letter: "G", color: "#EE99AC" }, "growlithehisui": { letter: "H", color: "#F08030" },
  "arcaninehisui": { letter: "H", color: "#F08030" }, "typhlosionhisui": { letter: "H", color: "#705898" }, "samurotthisui": { letter: "H", color: "#705848" },
  "zoruahisui": { letter: "H", color: "#A8A878" }, "zoroarkhisui": { letter: "H", color: "#A8A878" }, "braviaryhisui": { letter: "H", color: "#F85888" },
  "decidueyehisui": { letter: "H", color: "#C03028" }, "aegislashblade": { letter: "A", color: "#B8B8D0" }, "indeedeef": { letter: "I", color: "#F85888" },
  "palafinhero": { letter: "P", color: "#6890F0" }, "rotomwash": { letter: "R", color: "#6890F0" }, "rotomheat": { letter: "R", color: "#F08030" },
  "rotommow": { letter: "R", color: "#78C850" }, "rotomfrost": { letter: "R", color: "#98D8D8" }, "rotomfan": { letter: "R", color: "#A8A878" },
  "tatsugiridroopy": { letter: "T", color: "#7038F8" }, "tatsugiristretchy": { letter: "T", color: "#7038F8" }, "tatsugiricurly": { letter: "T", color: "#7038F8" },
  "abomasnowmega": { letter: "M", color: "#98D8D8" }, "absolmega": { letter: "M", color: "#705848" }, "absolz": { letter: "A", color: "#705848" },
  "aerodactylmega": { letter: "M", color: "#B8A038" }, "aggronmega": { letter: "M", color: "#B8B8D0" }, "alakazammega": { letter: "M", color: "#F85888" },
  "altariamega": { letter: "M", color: "#EE99AC" }, "ampharosmega": { letter: "M", color: "#7038F8" }, "audinomega": { letter: "M", color: "#EE99AC" },
  "banettemega": { letter: "M", color: "#705898" }, "barbaraclemega": { letter: "M", color: "#B8A038" }, "baxcaliburmega": { letter: "M", color: "#7038F8" },
  "beedrillmega": { letter: "M", color: "#A040A0" }, "blastoisemega": { letter: "M", color: "#6890F0" }, "blazikenmega": { letter: "M", color: "#F08030" },
  "cameruptmega": { letter: "M", color: "#F08030" }, "chandeluremega": { letter: "M", color: "#705898" }, "charizardmegax": { letter: "M", color: "#7038F8" },
  "charizardmegay": { letter: "M", color: "#F08030" }, "chesnaughtmega": { letter: "M", color: "#78C850" }, "chimechomega": { letter: "M", color: "#F85888" },
  "clefablemega": { letter: "M", color: "#EE99AC" }, "crabominablemega": { letter: "M", color: "#98D8D8" }, "delphomegax": { letter: "M", color: "#F85888" },
  "dragalgemega": { letter: "M", color: "#A040A0" }, "dragonitemega": { letter: "M", color: "#7038F8" }, "drampamega": { letter: "M", color: "#A8A878" },
  "eelektrossmega": { letter: "M", color: "#F8D030" }, "emboarmega": { letter: "M", color: "#F08030" }, "excadrillmega": { letter: "M", color: "#E0C068" },
  "falinksmega": { letter: "M", color: "#C03028" }, "feraligatrmega": { letter: "M", color: "#6890F0" }, "floettemega": { letter: "M", color: "#EE99AC" },
  "froslassmega": { letter: "M", color: "#705898" }, "gallademega": { letter: "M", color: "#C03028" }, "garchompmega": { letter: "M", color: "#7038F8" },
  "gardevoirmega": { letter: "M", color: "#EE99AC" }, "gengarmega": { letter: "M", color: "#705898" }, "glaliemega": { letter: "M", color: "#98D8D8" },
  "glimmoramega": { letter: "M", color: "#B8A038" }, "golisopodmega": { letter: "M", color: "#A8B820" }, "golurkmega": { letter: "M", color: "#E0C068" },
  "greninjamega": { letter: "M", color: "#6890F0" }, "gyaradosmega": { letter: "M", color: "#705848" }, "hawluchamega": { letter: "M", color: "#C03028" },
  "heracrossmega": { letter: "M", color: "#A8B820" }, "houndoommega": { letter: "M", color: "#705848" }, "kangaskhanmega": { letter: "M", color: "#A8A878" },
  "lopunnmegay": { letter: "M", color: "#C03028" }, "lucariomega": { letter: "M", color: "#B8B8D0" }, "lucarioz": { letter: "L", color: "#B8B8D0" },
  "malamarmega": { letter: "M", color: "#705848" }, "manectricmega": { letter: "M", color: "#F8D030" }, "mawilemega": { letter: "M", color: "#EE99AC" },
  "medichammega": { letter: "M", color: "#C03028" }, "meganiummega": { letter: "M", color: "#78C850" }, "meowsticmega": { letter: "M", color: "#F85888" },
  "metagrossmega": { letter: "M", color: "#B8B8D0" }, "pidgeotmega": { letter: "M", color: "#A8A878" }, "pinsirmega": { letter: "M", color: "#A8B820" },
  "pyroarmega": { letter: "M", color: "#F08030" }, "raichumegax": { letter: "M", color: "#F8D030" }, "raichumegay": { letter: "M", color: "#F8D030" },
  "sableyemega": { letter: "M", color: "#705848" }, "salamencemega": { letter: "M", color: "#7038F8" }, "sceptilemega": { letter: "M", color: "#7038F8" },
  "scizormega": { letter: "M", color: "#C03028" }, "scolipedemega": { letter: "M", color: "#A8B820" }, "scovillainmega": { letter: "M", color: "#78C850" },
  "scraftmegay": { letter: "M", color: "#705848" }, "sharpedomega": { letter: "M", color: "#6890F0" }, "skarmormegay": { letter: "M", color: "#B8B8D0" },
  "slowbromega": { letter: "M", color: "#6890F0" }, "staraptormega": { letter: "M", color: "#A8A878" }, "starmiemega": { letter: "M", color: "#6890F0" },
  "steelimegax": { letter: "M", color: "#B8B8D0" }, "swampertmega": { letter: "M", color: "#6890F0" }, "tyranitarmega": { letter: "M", color: "#705848" },
  "venusaurmega": { letter: "M", color: "#78C850" }, "victreebelmega": { letter: "M", color: "#78C850" },
  "calyrexice": { letter: "C", color: "#98D8D8" }, "urshifurapidstrike": { letter: "U", color: "#6890F0" }, 
  "ragingbolt": { letter: "R", color: "#F8D030" }, "ogerponhearthflame": { letter: "O", color: "#F08030" }, 
  "fluttermane": { letter: "F", color: "#705898" }, "ironhands": { letter: "I", color: "#C03028" }, 
  "landorustherian": { letter: "L", color: "#E0C068" }, "chienpao": { letter: "C", color: "#705848" }, 
  "calyrexshadow": { letter: "C", color: "#705898" }, "thundurus": { letter: "T", color: "#F8D030" }, 
  "zaciancrowned": { letter: "Z", color: "#B8B8D0" }, "groudon": { letter: "G", color: "#E0C068" }, 
  "kyogre": { letter: "K", color: "#6890F0" }, "tapufini": { letter: "T", color: "#6890F0" }, 
  "tapukoko": { letter: "T", color: "#F8D030" }, "kartana": { letter: "K", color: "#78C850" }, 
  "rayquaza": { letter: "R", color: "#7038F8" }, "hitmontop": { letter: "H", color: "#C03028" }, 
  "heatran": { letter: "H", color: "#F08030" }, "cresselia": { letter: "C", color: "#F85888" }, 
  "pachirisu": { letter: "P", color: "#F8D030" }
};

const ARCHETYPE_CORES = {
    "Bulky Offense": { setters: ["incineroar", "arcanine"], abusers: ["rillaboom", "gholdengo", "amoonguss", "dragonite"], megas: ["kangaskhanmega", "venusaurmega", "scizormega", "metagrossmega", "dragonitemega", "meganiummega", "feraligatrmega", "excadrillmega", "scraftymega", "chesnaughtmega", "golisopodmega", "baxcaliburmega", "lucariomegaz", "absolmegaz"], megaSetters: [] },
    "Rain": { setters: ["pelipper"], abusers: ["archaludon", "palafinhero", "basculegion", "gastrodon"], megas: ["swampertmega", "blastoisemega", "gyaradosmega", "starmiemega", "dragalgemega", "eelektrossmega"], megaSetters: [] },
    "Sun": { setters: ["torkoal", "ninetales"], abusers: ["venusaur", "charizard", "skeledirge", "scovillain"], megas: ["charizardmegay", "houndoommega", "victreebelmega", "emboarmega", "delphoxmega", "scovillainmega", "pyroarmega"], megaSetters: ["charizardmegay"] },
    "Sand": { setters: ["tyranitar"], abusers: ["excadrill", "garchomp"], megas: ["tyranitarmega", "garchompmega", "aerodactylmega", "excadrillmega", "barbaraclemega"], megaSetters: ["tyranitarmega"] },
    "Snow": { setters: ["ninetalesalola", "abomasnow"], abusers: ["baxcalibur", "glaceon", "froslass"], megas: ["abomasnowmega", "glaliemega", "froslassmega", "crabominablemega"], megaSetters: ["abomasnowmega"] },
    "Trick Room": { setters: ["hatterene", "farigiraf", "bronzong", "oranguru"], abusers: ["ursaluna", "torkoal", "amoonguss", "kingambit"], megas: ["cameruptmega", "mawilemega", "ampharosmega", "clefablemega", "golurkmega", "drampamega"], megaSetters: [] },
    "Tailwind": { setters: ["talonflame", "corviknight", "pelipper"], abusers: ["gholdengo", "arcanine", "hydreigon"], megas: ["salamencemega", "pidgeotmega", "aerodactylmega", "staraptormega", "raichumegax", "raichumegay", "hawluchamega", "skarmorymega"], megaSetters: [] },
    "Psyspam": { setters: ["indeedeef", "indeedee"], abusers: ["armarouge", "hatterene", "gallade"], megas: ["alakazammega", "medichammega", "metagrossmega", "gallademega", "chimechomega", "meowsticmega", "malamarmega"], megaSetters: [] }
};